Repository onlydustxyz/starklings, pull requests merged in 2022-05, with the labels that each got.

#103 doc: add discord link to readme
  README.md
Labels: type: docs, effort: 1, state: approved

#131 Add monitoring using Sentry
  poetry.lock
  pyproject.toml
  src/cli.py
Labels: Type: feature, Duration: under a day, Context: intricated, Difficulty: easy, Techno: python, State: in progress

#156 Fix: remove patch context
  .patches/beginner/ex02.cairo.patch
Labels: Not in changelog
